### ISSUE TITLE
basic question about fp16

### ISSUE THREAD

**Issue by Adorablepet** [NVlabs/DG-Net#11]
Hi，I installed `apex`. When I used `apex:True`, then appeared error about `value cannot be converted to type float without overflow`.
Error track：‘trainer.dis_update(images_a, images_b, config) -> scaled_loss.backward()’ 
Code environment：`Pytho: 3.6.8, CUDA: 9.0, Pytorch: 1.0.1 `
I don't know if you have ever met，Could you help me? Thanks.

**Comment by layumi** [comment]
Hi @Adorablepet 
Could you show me the complete log? Thank you.

**Comment by Adorablepet** [comment]
@layumi 
```` bash
Epoch: 00 Iteration: 00000094/00100000 DLoss: 5.9224 Reg: 0.0000
Elapsed time in upate: 0.364377
Traceback (most recent call last):
File "train.py", line 122, in <module>
trainer.dis_update(images_a, images_b, config)
File "./reid/DG-Net-master/trainer.py", line 644, in dis_update
scaled_loss.backward()
File "~/anaconda3/envs/temparch/lib/python3.6/contextlib.py" line 88, in __exit__
next(self.gen())
File "~/anaconda3/envs/temparch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64/apex/amp/handle.py", line 127 , in sacle_loss
optimizer.__post_amp_backward(loss_scaler)
File "~/anaconda3/envs/temparch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64/apex/amp/__process_optimizer.py", line 235, in post_backward_no_master_weights
grads_needing_unscal_with_stash)
File "~/anaconda3/envs/temparch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64/apex/amp/scaler.py", line 177, in unscale_with_stashed
scale)
....
File "~/anaconda3/envs/temparch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64/apex/amp/wrap.py", line 111, in wrapped
return orig_fn(arg0, *new_args, **kwargs)
previous line repeated 1 more time
RuntimeError: value cannot be converted to type float without overflow: 3.40282e+38
````

**Comment by layumi** [comment]
@Adorablepet 
It looks quite wired. Did the generation loss before the 94th iteration seems to be good?

Is there any warning when you install `apex` with `python setup.py install --cuda_ext --cpp_ext` ?

**Comment by Adorablepet** [comment]
@layumi yes, has some warnings, but I didn't care. Do you think it might be caused by these warnings? I will reinstall `apex`.

**Comment by Adorablepet** [comment]
@layumi I reinstalled several times in different environments.I don't think there should be much relationship with the installation.when installing, appeared warmings about `command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++`. I also used apex before, and there was no problem.So is there any other problem? Thanks.

**Comment by layumi** [comment]
- It looks like overflow. Did the generation loss before the 94th iteration seems to be good? 

- Have you try to run the code in different environments? Sorry. For the time being, I only tested the code on Ubuntu (cuda10 and pytorch1.0+) and did not meet any similar problems... So it is hard for me to debug this problem. More details are welcomed.

**Comment by Adorablepet** [comment]
@layumi I agree with `it looks like overflow`.
````
Epoch: 00 Iteration: 00000083/00100000 DLoss: nan Reg: nan
Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 2.938735877055719e-39
.....
````

**Comment by layumi** [comment]
Hi @Adorablepet 
I called my friend who works at company run my code with ~100 times. He hasn't reproduced your result under fp16 environment. He says fp16 looks good.
So could you show me the losses of the first 10 iterations? It may help me to know which loss probably causes the overflow problem.

**Comment by Adorablepet** [comment]
Hi @layumi 
Sorry, I have something late, forget about github.
````
DLoss:6.0000 Reg:0.0000
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 16384.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 16384.0
L_total:61.4591, L_gan:12.0000, Lx:8.2094, Lxp:8.1693, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6183, id:13.2236, pid:13.2385, teacher:0.0000
Elapsed time in update:6.298417

Epoch: 00 Iteration: 00000001/00100000 DLoss:nan Reg:nan
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 8192.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 4096.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 4096.0
L_total:62.4823, L_gan:12.0000, Lx:8.6944, Lxp:8.6846, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6186, id:13.2391, pid:13.2456, teacher:0.0000
Elapsed time in update:1.178141

Epoch: 00 Iteration: 00000002/00100000 DLoss:6.0000 Reg:0.0000
L_total:61.8670, L_gan:12.0000, Lx:8.3870, Lxp:8.3793, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6192, id:13.2304, pid:13.2512, teacher:0.0000
Elapsed time in update:1.142381

Epoch: 00 Iteration: 00000003/00100000 DLoss:6.0000 Reg:0.0000
L_total:60.6108, L_gan:12.0000, Lx:7.7385, Lxp:7.7454, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6239, id:13.2531, pid:13.2499, teacher:0.0000
Elapsed time in update:1.141909

Epoch: 00 Iteration: 00000004/00100000 DLoss:6.0000 Reg:0.0000
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 2048.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 2048.0
L_total:58.2253, L_gan:11.9998, Lx:6.5762, Lxp:6.5446, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6257, id:13.2415, pid:13.2375, teacher:0.0000
Elapsed time in update:1.056701

Epoch: 00 Iteration: 00000005/00100000 DLoss:nan Reg:nan
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 1024.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 512.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 512.0
L_total:58.1009, L_gan:11.9999, Lx:6.5097, Lxp:6.4772, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6282, id:13.2498, pid:13.2462, teacher:0.0000

Epoch: 00 Iteration: 00000006/00100000 DLoss:5.9998 Reg:0.0000
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 256.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 256.0
L_total:58.6653, L_gan:11.9883, Lx:6.8467, Lxp:6.8305, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6439, id:13.1375, pid:13.2185, teacher:0.0000
Elapsed time in update:0.976348

Epoch: 00 Iteration: 00000007/00100000 DLoss:nan Reg:nan
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 128.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 64.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 64.0
L_total:59.8318, L_gan:11.9883, Lx:7.3467, Lxp:7.4077, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6249, id:13.2512, pid:13.2127, teacher:0.0000
Elapsed time in update:1.023993

Epoch: 00 Iteration: 00000008/00100000 DLoss:nan Reg:nan
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 32.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 16.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 16.0
L_total:58.8324, L_gan:11.9883, Lx:6.9279, Lxp:6.8785, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6199, id:13.2098, pid:13.2080, teacher:0.0000
Elapsed time in update:1.031439

Epoch: 00 Iteration: 00000009/00100000 DLoss:nan Reg:nan
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 8.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 4.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 4.0
L_total:59.4917, L_gan:11.9883, Lx:7.1263, Lxp:7.2408, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6116, id:13.2799 pid:13.2448, teacher:0.0000
Elapsed time in update:1.024513

Epoch: 00 Iteration: 00000010/00100000 DLoss:5.9941 Reg:0.0000
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 2.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 2.0
L_total:58.2244, L_gan:11.9883, Lx:6.5771, Lxp:6.5289, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.5154, id:13.2564 pid:13.2583, teacher:0.0000
Elapsed time in update:0.990972

Epoch: 00 Iteration: 00000011/00100000 DLoss:5.9941 Reg:0.0000
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 1.0
Gradient overflow, skipping step, loss scaler 0 reducing loss scale to 1.0
L_total:58.9748, L_gan:11.9883, Lx:6.9835, Lxp:7.0655, Lrecycle:0.0000, Lf:0.0000, Ls:0.0000, Recon-id:6.6136, id:13.1822 pid:13.1416, teacher:0.0000
Elapsed time in update:0.988119
````
thanks!

**Comment by layumi** [comment]
@Adorablepet 
The error seems to be the `nan` of D loss in the first iteration. It is weird..... Could you check the downloaded data? Are they broken?

**Comment by Adorablepet** [comment]
@layumi 
I downloaded market1501 again，but still appeared the same error.
I trained the following command, it's OK.
`python train.py --config configs/latest.yaml`
But the following command, it's not OK.
`pytho train.py --config configs/latest-fp16.yaml`
So I think I downloaded data no problem.

````
train environment/coda
ubuntu: 16.04
pytorch: 1.0.1
python: 3.6.8
cuda: 9.0
cudnn: 7.3.1 
gpu: v100
````
I copy files from your `baiduyun` downloaded DG-Net.zip
`./models/best/net_last.pth`
`./models/best/opts.yaml`

**Comment by layumi** [comment]
Thanks a lot for your detailed report.

1. Could you try my another repo with fp16? It is more easy to identify whether the error is related to `apex` or cuda. 
https://github.com/layumi/Person_reID_baseline_pytorch 
```
python train.py --name fp16 --fp16
```

2. Could you find which variable become `nan` at the first iteration? It would be really helpful.

**Comment by Adorablepet** [comment]
@layumi 
1.
I trained completely about `Person_reID_baseline_pytorch`, and not appear `nan`.
So I think `apex` and `cuda` have no problem.
````
Epoch 59/59
train_loss:0.0205 Acc: 0.9979
val_loss: 0.2508 Acc: 0.9374
Training complete in 31m 23s
````
2.
 `trainer.py->def dis_update( )->self.loss_dis_a, self.loss_dis_b, reg_a, reg_b=nan,nan,nan,nan`
but `x_ba.detach( ), x_a, x_ab.detach( ), x_b` have tensor value.
So is it caused by these codes?
`networks.py->def calc_dis_loss( )` `118-121 lines`
````
if self.gan_type == 'lsgan':
   loss += torch.mean((out0-0)**2) + torch.mean((out1-1)**2)
   reg += LAMBDA*self.compute_grad2(out1, input_real).mean()
````
thanks

**Comment by layumi** [comment]
Could you try modify the code as following?
```python
if self.gan_type == 'lsgan':
   loss += torch.mean((out0.float()-0)**2) + torch.mean((out1.float()-1)**2)
   reg += LAMBDA*self.compute_grad2(out1, input_real).float().mean()
```

**Comment by Adorablepet** [comment]
@layumi 
I try it, still appear the same error.

**Comment by layumi** [comment]
Does `out0 `, `out1` show a regular result?

**Comment by Adorablepet** [comment]
@layumi  Yes, I print it, tensor value,

**Comment by layumi** [comment]
Would you like to print `torch.mean((out0.float()-0)**2)` ?
```python
print( torch.mean((out0.float()-0)**2) , torch.mean((out1.float()-1)**2 ) )
if self.gan_type == 'lsgan':
   loss += torch.mean((out0.float()-0)**2) + torch.mean((out1.float()-1)**2)
   reg += LAMBDA*self.compute_grad2(out1, input_real).mean()
```

**Comment by Adorablepet** [comment]
@layumi 
appear `nan`, print it as following, other values are close.
````
print(torch.mean((out0.float()-0)**2))
tensor(1.9329e-10,device='cuda:0')

print(torch.mean((out1.float()-1)**2))
tensor(0.9999,device='cuda:0')
````

**Comment by layumi** [comment]
```python
if self.gan_type == 'lsgan':
   loss += torch.mean((out0.float()-0)**2) + torch.mean((out1.float()-1)**2)
   print(loss)
   reg += LAMBDA*self.compute_grad2(out1, input_real).mean()
   print(reg)
```

**Comment by Adorablepet** [comment]
````
print(loss)
tensor(2.9518, device='cuda:0')

print(reg)
tensor(nan, device='cuda:0')
DLoss; nan  Reg:nan
````

**Comment by layumi** [comment]
Could you try the following code AT https://github.com/NVlabs/DG-Net/blob/2c339f83ab70d610615bf7b89894c31729602007/networks.py#L155 ? 

grad_dout2 = grad_dout.float().pow(2)

```python 
    def compute_grad2(self, d_out, x_in):
        batch_size = x_in.size(0)
        grad_dout = torch.autograd.grad(
            outputs=d_out.sum(), inputs=x_in,
            create_graph=True, retain_graph=True, only_inputs=True
        )[0]
        print(grad_dout)
        grad_dout2 = grad_dout.float().pow(2)
        assert(grad_dout2.size() == x_in.size())
        reg = grad_dout2.view(batch_size, -1).sum(1)
        return reg
```

**Comment by Adorablepet** [comment]
````
print(grad_dout)
tensor([nan]....)

print(grad_dout2)
tensor([nan]....)
````

**Comment by layumi** [comment]
```python
        print(d_out)
        grad_dout = torch.autograd.grad(
            outputs=d_out.float().sum(), inputs=x_in,
            create_graph=True, retain_graph=True, only_inputs=True
        )[0]
        print(grad_dout)
```

**Comment by Adorablepet** [comment]
````
print(d_out)
tensor([[[[0.0065, 0.0065, 0.0065...]...]...]...])
tensor([[[[0.0052, 0.0052, 0.0052...]...]...]...])
tensor([[[[0.0059, 0.0059, 0.0059...]...]...]...])
.....
````

**Comment by layumi** [comment]
So `grad_dout` is still `nan` ? 
I am not sure what is happened to  ` torch.autograd.grad`. The first thing we could try is to turn off the fp16 for discriminator. 
Please comment this line to see the difference.
https://github.com/NVlabs/DG-Net/blob/master/trainer.py#L312

**Comment by Adorablepet** [comment]
@layumi 
1 Yes.
2 I try to turn off the fp16 for discriminator.
````
trainer.py/dis_update()
if self.fp16:
  with amp.scale_loss(self.loss_dis_total, self.dis_opt) as scaled_loss:
         scaled_loss.backward()
else:
   self.loss_dis_total.backward()
modify it as following:
self.loss_dis_total.backward()
````
print(grad_dout)
it is not `nan`,
DLoss:1.3914 Reg:1.061604,
But still appear the same error.

**Comment by layumi** [comment]
Which error this time? Which loss became `nan`?

**Comment by sky186** [comment]
@layumi
您好，谢谢您的工作，这个方法很好，后面如果能够继续优化就更好了，目前我还有一点问题想请教您
1、teacher model ， 截至到 现在，又出现了很多性能更好的reid 模型， 例如fastreid ,可以直接替换修改使用吗？
2、换数据，换模型之后，调整参数 有合适的参考标准吗？
3、方法是否具有普遍有效性昵， 例如reid  相关任务，造数据，是不是都可以这么尝试。
4、还有什么更好的优化方向吗？让数据生成的效果更好？

**Comment by sky186** [comment]
@layumi 
1、我想用您的工程，造一批reid 数据， 每个id 图片，生成该id 图片 各种换衣服的图片，例如论文中图1,显示的列方向图片，然后只用reid 的任务训练，   show1by1.py  中有这样实现，16个不同的人， 会生成16*16张 图片  ， 现在如果对market 数据进行数据， 输入751张图片，得到 751*751张合成的图片，      这边输入图片数量是否有限制？  对输入的图片种类是否有限制（因为都是随机选择的图片，图片有的会类似）
